global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s

scrape_configs:
  - job_name: weather
    metrics_path: /metrics
    static_configs:
      - targets:
          - weather:8080
